name: Release Creator
description: Create a tag and a Release for the specific project
inputs:
  version:
    type: string
    required: true
    description: Version
runs:
  using: "composite"
    steps:
    
    - name: Create tag and GitHub release
      if: ${{ github.ref == 'main' }}
      uses: actions/create-release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
