# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Version Checker
description: Check the version of the .csproj file
outputs:
  version: ${{ steps.get-version.outputs.version }}
runs:
  using: "composite"
  steps:
  
  - name: Check Project Version
    uses: kzrnm/get-net-sdk-project-versions-action@v1.1.2
    id: get-version
    with:
      proj-path: src/src.csproj
