name: CI - RC

on:
  push:
    branches:
      - rc
      
jobs:
  build:
    name: Build, Pack and Push - RC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        
      - name: GitHub NuGet Source
        run: dotnet nuget add source $source -n github --username albedocodes --password $api_key --store-password-in-clear-text
        env:
          source: ${{ secrets.NUGET_SOURCE }}
          api_key: ${{ secrets.NUGET_API_KEY }}

      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Debug --no-restore

      - name: Version Checker
        uses: ./.github/actions/version-checker
        id: version-checker
        
      - name: Create Timestamp
        id: timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
        
      - name: Pack
        run: | 
          dotnet pack --no-build --no-restore \
          --output package \
          --configuration Debug \
          /p:Version=$version.$timestamp-rc \
        env:
          version: ${{ steps.version-checker.outputs.version }}
          timestamp: ${{ steps.timestamp.outputs.timestamp }}
        
      - name: Push
        run: |
          dotnet nuget push \
          package/$namespace.$version.$timestamp-rc.nupkg \
          --source $source \
          --api-key $api_key \
        env:
          version: ${{ steps.version-checker.outputs.version }}
          timestamp: ${{ steps.timestamp.outputs.timestamp }}
          namespace: ${{ secrets.PROJECT_NAMESPACE }}
          source: ${{ secrets.NUGET_SOURCE }}
          api_key: ${{ secrets.NUGET_API_KEY }}
        

