name: Release Creator

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: Version
    
jobs:
  release-creator:
    name: Release Creator
    runs-on: ubuntu-latest
    steps:
    
    - name: Create tag and GitHub release
      if: ${{ github.ref == 'main' }}
      id: create_tag_and_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
